### ISSUE TITLE
bug：悬浮在角落时，不会自动调整位置

### ISSUE THREAD

**Issue by yzchen0o0** [tylermzeller/floaty#1]
首先，感谢作者的分享！
效果很好，但发现一个bug，就是当拖拽到一个角落时，js不会自动调整位置。
![bug1](https://cloud.githubusercontent.com/assets/3949164/18415350/279d9312-7821-11e6-9cb7-54f14f110628.png)

**Comment by tylermzeller** [comment]
Wow! Thanks for using Floaty, and thanks for opening this! This issue also appears if you drag a floaty to the edge, and then expand or shrink the floaty. Floaties currently don't automatically alter there positions, they must be be interacted with first.
